### ISSUE TITLE
Wrong link to sample-auction-app

### ISSUE THREAD

**Issue by inaridiy** [InternetMaximalism/intmax-interoperability-plugin#5]
I think the rick to sample-auction-app in readme.md is wrong.

Now the following link is set.
https://github.com/InternetMaximalism/intmax-rollup-cli-flag/tree/main/packages/sample-auction-app/ethereum
However, accessing it returns a 404 error.

From my own research, the following link is correct? I think so.
https://github.com/InternetMaximalism/intmax-rollup-cli/tree/main/packages/sample-auction-app/ethereum

**Comment by hrmk1o3** [comment]
Fix at e92ae2df7717b04c038100b9c1f41412b52cba75
